const quotes = [
    "Believe you can and you're halfway there",
"The only way to do great work is to love what you do",
"Success is not final, failure is not fatal It is the courage to continue that counts",
"The harder you work for something, the greater you'll feel when you achieve it",
"It always seems impossible until it’s done",
"Don’t watch the clock; do what it does. Keep going",
"Start where you are. Use what you have. Do what you can",
"Dream big and dare to fail",
"You are stronger than you think",
"Success is the sum of small efforts, repeated day in and day out",
"The future depends on what you do today",
"Act as if what you do makes a difference. It does",
"Push yourself, because no one else is going to do it for you",
"Don’t stop when you’re tired. Stop when you’re done",
"Believe in yourself and all that you are",
"The best way to predict the future is to create it",
"Hardships often prepare ordinary people for an extraordinary destiny",
"Success doesn’t come from what you do occasionally, it comes from what you do consistently",
"Make today count",
"You don’t have to be great to start, but you have to start to be great",
"Success is not in what you have, but who you are",
"Do something today that your future self will thank you for",
"The only limit to our realization of tomorrow is our doubts of today",
"You are never too old to set another goal or to dream a new dream",
"Small steps every day",
"Don't wait for opportunity. Create it",
"The journey of a thousand miles begins with one step",
"Success is walking from failure to failure with no loss of enthusiasm",
"Everything you need is already inside you",
"The secret of getting ahead is getting started",
"Good things come to those who hustle",
"It’s not whether you get knocked down, it’s whether you get up",
"You are capable of more than you know",
"Great things never come from comfort zones",
"In the middle of difficulty lies opportunity",
"Stay positive, work hard, make it happen",
"Your limitation—it’s only your imagination",
"Dream it. Wish it. Do it",
"Success is not how high you have climbed, but how you make a positive difference to the world",
"What we think, we become",
"Don’t limit your challenges. Challenge your limits",
"Wake up with determination. Go to bed with satisfaction",
"Everything you can imagine is real",
"The key to success is to focus on goals, not obstacles",
"The only way to achieve the impossible is to believe it is possible",
"Your attitude determines your direction",
"Do what you can with all you have, wherever you are",
"The only person you are destined to become is the person you decide to be",
"Success doesn’t just find you. You have to go out and get it",
"Keep your face always toward the sunshine—and shadows will fall behind you",
"Doubt kills more dreams than failure ever will",
"Be the change that you wish to see in the world",
"Opportunities don’t happen, you create them",
"Little by little, one travels far",
"If you want to achieve greatness stop asking for permission",
"Don’t wait. The time will never be just right",
"You don’t have to be perfect to be amazing",
"The only thing standing between you and your goal is the story you keep telling yourself",
"Believe in yourself and you will be unstoppable",
"If you want it, work for it",
"The best time to plant a tree was 20 years ago. The second best time is now",
"Stay focused and never give up",
"Work hard in silence, let your success be your noise",
"The only way to fail is to quit",
"It’s never too late to be what you might have been",
"Don’t be afraid to give up the good to go for the great",
"Life is 10% what happens to us and 90% how we react to it",
"Success is the sum of small efforts, repeated day in and day out",
"Keep going. Everything you need will come to you at the perfect time",
"Don’t wait for the right moment. Take the moment and make it right",
"The mind is everything. What you think you become",
"You’re braver than you believe, stronger than you seem, and smarter than you think",
"Success doesn’t come from what you do occasionally, it comes from what you do consistently",
"You’re not a failure until you give up",
"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
"It’s never crowded along the extra mile",
"Hard work beats talent when talent doesn’t work hard",
"Be yourself; everyone else is already taken",
"Do one thing every day that scares you",
"If you’re going through hell, keep going",
"The best is yet to come",
"You only fail when you stop trying",
"Success is a journey, not a destination",
"A goal without a plan is just a wish",
"The best way to get started is to quit talking and begin doing",
"Success is not for the chosen few, but for those who choose it",
"The only way to grow is to step out of your comfort zone",
"It’s going to be hard, but hard does not mean impossible",
"You are capable of achieving greatness",
"Small daily improvements over time lead to stunning results",
"Success is the sum of small efforts, repeated",
"You are the only one who can limit your greatness",
"Stay strong. Stay positive. Stay focused",
"Do what you love, love what you do",
"Success is what happens after you have survived all your mistakes",
"The way to get started is to quit talking and begin doing",
"You don’t have to be perfect to be amazing",
"Success is not how high you have climbed, but how you make a positive difference to the world",
"The best revenge is massive success",
"Push harder than yesterday if you want a different tomorrow",
    
];

document.getElementById('generate-quotes').addEventListener('click', function() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById('quotes-display').textContent = quotes[randomIndex];
});
